name: Bump to major version and push Dlite
on:
  workflow_dispatch:

jobs:
  generate_and_push_dlite:
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup node
        id: step1
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true
          registry-url: "https:registry.npmjs.org"
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          ref: 'develop'
      - name: Setup build
        id: step2
        run: |
          npm install
          npm run build
      - name: Bump version and create PR
        id: step3
        run: |
          npm install -g json@latest
          
          old_version=$(json -f ./package.json version)
          
          head="dlite/$new_version"
          if [ $(git ls-remote origin "$head") ]; then
            git push origin -d "$head"
          fi
          
          git checkout -b "$head"
          npm version major
          new_version=$(json -f ./package.json version)
          npm install -g json@latest
          
          git config --global user.name ${{ secrets.GH_USERNAME }}
          git config --global user.email ${{ secrets.GH_EMAIL }}
          
          git checkout -b "$head" develop
          npm version major
          
          new_version=$(json -f ./package.json version)
          git commit -a -m "feat: Bump version from $old_version to $new_version." --allow-empty
          git push origin "$head"
          pr_body=$(git diff HEAD..main)
          
          sudo apt install gh
          gh auth login --with-token <<< ${{ github.token }}
          gh pr create --title "Bump dlite from $old_version to $new_version" --body "$pr_body" --base "main" --head "$head"

          
          
      
          
        
    
